### PR TITLE
Escape first quotes in all occurences of "channel"

### LINKED ISSUE #2: Fail2ban jail, Unexpected end of file, escape double-quote for channel
Hi,

thanks for doing all the work. It's a cool implementation.

I had to escape another quote though, cause I was getting an error:

```
2020-02-28 14:50:34,465 fail2ban.utils          [8497]: ERROR   7f01ae0cf430 -- exec: curl -s -o /dev/null -X POST --data-urlencode "payload={\"text\": \"Fail2Ban (sshd) jail has started\", "channel\": \"#notifications\" }" 'https://hooks.slack.com/services/some-token-for-slack'
2020-02-28 14:50:34,466 fail2ban.utils          [8497]: ERROR   7f01ae0cf430 -- stderr: '/bin/sh: -c: line 0: unexpected EOF while looking for matching `"\''
2020-02-28 14:50:34,466 fail2ban.utils          [8497]: ERROR   7f01ae0cf430 -- stderr: '/bin/sh: -c: line 1: syntax error: unexpected end of file'
2020-02-28 14:50:34,466 fail2ban.utils          [8497]: ERROR   7f01ae0cf430 -- returned 1
2020-02-28 14:50:34,466 fail2ban.actions        [8497]: ERROR   Failed to start jail 'sshd' action 'slack-notify': Error starting action Jail('sshd')/slack-notify: 'Script error'
```

So in `slack-notify.conf`, just escape the double-quote for channel, so
```
, "channel\": 
```
becomes
```
, \"channel\": 
```

Best regards,

Raz

### PR DESCRIPTION
**Pull request by maresb**
Fixes #2.

(Sorry about all the noise from those other flawed pull requests.)

### CODE REVIEW

**Comment by ionescu77** [comment]
Sounds pretty much consitent with my findings, this should fix my opened Issue #2
I already had this local on my server.

**Comment by bguerout** [comment]
+1 Fix the broken conf file

**Comment by maresb** [comment]
Ping @coleturner?  All I'm doing here is escaping some backslashes.

**Review by coleturner — APPROVED** [review]

**Comment by coleturner** [comment]
Apologies for the late reply, life gets busy on me. Nice work!

**Comment by maresb** [comment]
Awesome, thanks so much!!! Great instructions!

**Pull request merged**
